import { useState, useEffect } from 'react';
import { api } from '../services/api';

// This VAPID public key is used by the push service to identify your application.
// It should be generated by your backend (e.g., using the 'web-push' library)
// and stored as an environment variable. It is safe to expose on the frontend.
const VAPID_PUBLIC_KEY = 'BOi9nl-6m_UC3GD_3H-Pql75eK7CbR-52rTRmKO3t00l-zD2jEC2Z3q5t4w7u8_9v0aBcDef_1g2h3j4k5l6m7n8';

/**
 * Converts a VAPID key from a URL-safe base64 string to a Uint8Array.
 * This is required by the PushManager subscribe method.
 */
function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - base64String.length % 4) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export const usePushNotifications = () => {
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [subscription, setSubscription] = useState<PushSubscription | null>(null);
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(true);

  // Check for an existing subscription when the hook mounts.
  useEffect(() => {
    const checkSubscription = async () => {
      if ('serviceWorker' in navigator && 'PushManager' in window) {
        try {
          const registration = await navigator.serviceWorker.ready;
          const sub = await registration.pushManager.getSubscription();
          if (sub) {
            setIsSubscribed(true);
            setSubscription(sub);
          }
        } catch (err) {
            console.error('Error checking push subscription:', err);
            setError(err instanceof Error ? err : new Error('Unknown error checking subscription'));
        }
      }
      setLoading(false);
    };
    checkSubscription();
  }, []);

  /**
   * Subscribes the user to push notifications.
   */
  const subscribeToPush = async () => {
    if (isSubscribed) return;
    setError(null);
    setLoading(true);

    try {
      const registration = await navigator.serviceWorker.ready;
      const sub = await registration.pushManager.subscribe({
        userVisibleOnly: true, // A requirement for most browsers.
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
      });
      
      // Send the new subscription to the backend to be stored.
      await api.savePushSubscription(sub);
      
      setSubscription(sub);
      setIsSubscribed(true);
    } catch (err) {
        console.error('Failed to subscribe to push notifications:', err);
        const typedError = err instanceof Error ? err : new Error('Failed to subscribe');
        if (Notification.permission === 'denied') {
            setError(new Error('A permissão para notificações foi negada. Você precisa habilitá-la nas configurações do seu navegador.'));
        } else {
             setError(typedError);
        }
    }
    setLoading(false);
  };

  /**
   * Unsubscribes the user from push notifications.
   */
  const unsubscribeFromPush = async () => {
    if (!subscription) return;
    setError(null);
    setLoading(true);

    try {
        // Tell the backend to remove the subscription.
        await api.removePushSubscription(subscription.endpoint);
        // Unsubscribe from the browser's push service.
        await subscription.unsubscribe();

        setSubscription(null);
        setIsSubscribed(false);
    } catch (err) {
        console.error('Failed to unsubscribe from push notifications:', err);
        setError(err instanceof Error ? err : new Error('Failed to unsubscribe'));
    }
    setLoading(false);
  };
  
  // Check if the browser has the necessary APIs for push notifications.
  const isSupported = 'serviceWorker' in navigator && 'PushManager' in window;

  return { isSubscribed, subscribeToPush, unsubscribeFromPush, error, loading, isSupported };
};
